name: Haskell with cabal-install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - ghc: '8.8.4'
            cabal-install: '3.0.0.0'
          - ghc: '8.6.5'
            cabal-install: '2.4.0.0'
          - ghc: '8.4.4'
            cabal-install: '2.2.0.0'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal-install }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        set -ex
        cabal new-update
        if [ -r cabal.project ]; then
          target=all
        else
          target=
        fi
        cabal new-build --jobs=2 --only-dependencies --enable-tests --enable-benchmarks $target
    - name: Build
      run: |
        set -ex
        if [ -r cabal.project ]; then
          target=all
        else
          target=
        fi
        cabal new-build --jobs=2 --enable-tests --enable-benchmarks $target
    - name: Run tests
      run: |
        set -ex
        if [ -r cabal.project ]; then
          target=all
        else
          target=
        fi
        cabal new-test $target

### Local Variables: ***
### mode:yaml ***
### indent-tabs-mode: nil ***
### End: ***
